language: java

jdk:
  - oraclejdk8

services:
  - docker

jobs:
  include:
    - stage: test
      script: 
        - ./mvnw test
    - stage: deploy
      script:
        - ./mvnw package
        - docker build -t stefan314/proep-backend .
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker push stefan314/proep-backend

