language: java

jdk:
  - oraclejdk8

services:
  - docker

cache:
  directories:
    - $HOME/.m2

env:
  - DOCKER_IMAGE=stefan314/proep_backend

jobs:
  include:
    # - stage: test
    #   script: 
    #     - ./mvnw test
    - stage: deploy
      script:
        - ./mvnw package
        - ./scripts/docker_push.sh
