app:
  name: anuglar2-spring-jwt

jwt:
  header: Authorization
  expires_in: 600 # 10 minutes
  secret: queenvictoria
  cookie: AUTH-TOKEN

logging:
  level:
    org.springframework.web: ERROR
    com.bfwg: DEBUG

spring:
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    username: goairrnd@gmail.com
    password: HELLO_thisisairrnd1
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    protocol: smtp
    test-connection: false